name: "Podcast Generator"
author: "Deepanshu Jain"
description: "Feed generator"
runs: 
  using: "Docker"
  image: "Dockerfile"
branding:
  icon: "git branch"
  color: "red"
inputs:
  email: 
    description: The committer email
    rquired: true
    default: ${{github_actor}}@localhost
  name:
    description: The committer name
    required: true
    default: ${{github_actor}}
